/* Usuarios y roles */

INSERT INTO usuarios(username, password, enabled, nombre, apellido, email) VALUES ('ignacio', '$2a$10$ypUIbnJJ8wboDtNkc1UST.C7dGNvzvLtQS7GkEVAHxSgFns5ceqhK',1,"Ignacio","Maldonado","maildeignacio@test.com");
INSERT INTO usuarios(username, password, enabled, nombre, apellido, email) VALUES ('Cristian', '$2a$10$Nk.F.aFwZDnEP7DbrW/yQeByIFjXHX5c/Hby.dgUgZpREupDeh8Ke',1,"Cristian","Maldonado","maildecristian@test.com");

INSERT INTO roles(nombre) VALUES('ROLE_REPARTIDOR');
INSERT INTO roles(nombre) VALUES('ROLE_OPERADOR');

INSERT INTO usuarios_roles (usuario_id, role_id) VALUES(1, 1);
INSERT INTO usuarios_roles (usuario_id, role_id) VALUES(2, 2);

/* Productos */
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Master Cat sabor pollo, contiene fibras naturales que promueven una digestión sana y estimulan el desplazamiento de las bolas de pelo a través del sistema digestivo, previniendo el estreñimiento en tu gato. Además contiene Omega 3 que permite mantener una piel sana y un pelaje brillante.','Champion Cat Pollo','1800','20','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-perro','Purina® DOG CHOW® Adulto con Pollo, es una nutrición adaptada para perros adultos que incluye vitaminas y minerales esenciales para apoyar huesos saludables y altos niveles de proteínas y grasas para mantener el mantenimiento muscular. Con Antioxidantes.','Purina DOG CHOW Adulto Pollo','3600','30','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('accesorios','Este arnés mantiene a tu gato cómodo mientras camina. Su diseño innovador distribuye la presión de la correa en el cuello y los hombros de manera uniforme para un control suave. La circunferencia se ajusta de 35 a 40 cm para proporcionar un ajuste seguro y cómodo.','COASTAL COMFORT SOFT ARNES ROJO','3600','30','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('antiparasitario','BRAVECTO es el único comprimido palatable que protege a tu perro hasta 12 semanas contra pulgas y garrapatas. Antiparasitario externo con forma de comprimido masticable que sirve para la prevención, control y tratamiento de infestaciones de pulgas y garrapatas en perros.','Bravecto Antiparasitario Externo para Perros','27990','50','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Alimento seco para gatos adultos de todas las razas PRO PLAN®. Con probióticos que optimizan la digestión y la absorción de nutrientes. En formato de 7.5 kg.','Pro Plan Gato Adulto de Todas las Razas, 7.5 kg','50890','25','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Purina Cat Chow adultos delicias sabor a carne con Defense Plus, ofrece los nutrientes que tu gato necesita para ayudarlo a mantenerse fuerte y saludable. Su fórmula contiene entre sus ingredientes proteínas de la carne naturalmente ricas en hierro.','Alimento gato adulto carne 8 kg','20290','15','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Dale a tu gato la alimentación ideal para cada etapa de su vida. Diferentes estilos de vida, diferentes fórmulas. Purina Cat Chow adultos pescado ofrece un alimento rico en vitaminas y antioxidantes con el equilibrio perfecto de proteínas.','Alimento gato adulto pescado 8 kg','20792','20','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Alimento para gatos a partir de la castración (adultos y gatitos) de todos los tamaños CAT CHOW® Esterilizado/Castrados Pescado. Control de peso y músculos fuertes. Con prebiótico natural. Sin colorantes ni sabores artificiales. 100% completo y balanceado. En formato de 3kg.','Alimento gato adulto esterilizado defense plus 8kg','20290','20','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Sabemos que la relación que tienes con tu gato es muy especial, por eso el nuevo Purina Cat Chow adultos delimix con Defense Plus ofrece los nutrientes que tu gato necesita para mantenerse fuerte y saludable.','Alimento gato adulto Deli Mix 8kg','20290','21','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','El Sobrecito Whiskas es alimento húmedo nutricionalmente 100% completo y balanceado cocido al vapor, que contiene suaves trocitos en salsa y ha sido formulado para gatos adulto','Alimento húmedo gato adulto salsa carne 85g','750','60','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','El Sobrecito Whiskas es alimento húmedo nutricionalmente 100% completo y balanceado cocido al vapor, que contiene suaves trocitos en salsa y ha sido formulado para gatos adultos','Alimento húmedo gato adulto salsa pollo 85 g','750','40','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','El Sobrecito Whiskas es alimento húmedo nutricionalmente 100% completo y balanceado cocido al vapor, que contiene suaves trocitos en salsa y ha sido formulado para gatos adultos','Alimento húmedo gato adulto salsa sardina 85g','750','30','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Elige un alimento premium para tus gatos adultos. Master Cat sabor pollo, es completo y balanceado, con un 32% más de proteínas. Por un pelaje sano y brillante y un sano control urinario.','Alimento gato adulto pollo carne y leche 3kg','10490','20','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-gato','Fancy Feast filetes de atún, son exquisitos trozos de atún cocinados delicadamente. Posee un sabor único y superior, con texturas que crean una experiencia culinaria para tu gato.','Alimento húmedo gato petit filets de atún 85 g','2000','15','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-perro','Ingredientes: Maíz y/o trigo, harina de soya, harina de subproductos de aves, harinas de vísceras de pavo, grasa animal preservada con antioxidantes (aceite de pollo y/ grasa de cerdo), sebo bovino, harina de carne y hueso bovino, gluten meal, harina.','Alimento perro adulto raza mediana y grande 15kg','24290','10','', 'Activo');
INSERT INTO producto(categoria, descripcion, nombre, precio, stock, image_name, estado) VALUES('alimento-perro','Ingredientes: Maíz y/o trigo, harina de soya, harina de subproductos de aves, harinas de vísceras de pavo, grasa animal preservada con antioxidantes (aceite de pollo y/ grasa de cerdo), sebo bovino, harina de carne y hueso bovino, gluten meal, harina.','Alimento perro adulto raza pequeña 3 kg','24290','10','', 'Activo');


/* clientes */
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Martinez','Travessera Jimena, 5, 68º 2º','urena.alonso@example.org','Inactivo','Jose','+56966977720');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Ramirez','Paseo César, 9, 04º F','barrera.jana@example.org','Activo','Pedro','+56991909441');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Muñoz','Avinguda Luján, 85, 10º 7º','riera.sandra@example.com','Activo','Maria','+56966896219');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Saavedra','Rúa Zamora, 388, 7º','saavedra.carlos@example.org','Activo','Carlos','+56968010106');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Fuentes','Rúa Cristina, 487, 88º E','carla17@example.net','Inactivo','Carla','+56994272706');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Villanueva','Camino Águilar, 435, Bajo 3º','villanueva.isaac@example.org','Activo','Isaac','+56992186822');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Fuentes','Paseo Laura, 5, 2º','jesus21@example.com','Activo','Eduardo','+56917481230');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Bustos Péndola','Los Copihues 487','francisca@outlook.com','Activo','Francisca','+56984608425');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Maldonado','Villa Altue Pasaje Antillal 992','nachomaldo@outlook.com','Activo','Ignacio','+56954756427');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('fernandez','villa alegria 887','pe.fern887@outlook.com','Activo','pedro','+56956478921');
INSERT INTO cliente(apellido, direccion, email, estado, nombre, telefono) VALUES('Bustos Henríquez','Psje. Tomas Delphin 520 Villa Don Ambrosio','victor@gmail.com','Activo','Victor','+56995316468');